
CREATE OR REPLACE TABLE `ppdb-dev-438721.ppdb_dev.metadata` (
	`name` STRING NOT NULL OPTIONS(description='Name or key for a metadata item.'), 
	`value` STRING NOT NULL OPTIONS(description='Content of the metadata item in string representation.')
) OPTIONS(description='Table containing various metadata key:value pairs for APDB.')



--------------------------------------------------------------------------------


CREATE OR REPLACE TABLE `ppdb-dev-438721.ppdb_dev.DiaObject` (
	`diaObjectId` INT64 NOT NULL OPTIONS(description='Unique identifier of this DiaObject.'), 
	`validityStart` TIMESTAMP NOT NULL OPTIONS(description='Processing time when validity of this diaObject starts.'), 
	`validityEnd` TIMESTAMP OPTIONS(description='Processing time when validity of this diaObject ends.'), 
	`ra` DOUBLE NOT NULL OPTIONS(description='Right ascension coordinate of the position of the object at time radecMjdTai.'), 
	`raErr` FLOAT64 OPTIONS(description='Uncertainty of ra.'), 
	`dec` DOUBLE NOT NULL OPTIONS(description='Declination coordinate of the position of the object at time radecMjdTai.'), 
	`decErr` FLOAT64 OPTIONS(description='Uncertainty of dec.'), 
	`ra_dec_Cov` FLOAT64 OPTIONS(description='Covariance between ra and dec.'), 
	`radecMjdTai` DOUBLE OPTIONS(description='Time at which the object was at a position ra/dec, expressed as Modified Julian Date, International Atomic Time.'), 
	`pmRa` FLOAT64 OPTIONS(description='Proper motion in right ascension.'), 
	`pmRaErr` FLOAT64 OPTIONS(description='Uncertainty of pmRa.'), 
	`pmDec` FLOAT64 OPTIONS(description='Proper motion of declination.'), 
	`pmDecErr` FLOAT64 OPTIONS(description='Uncertainty of pmDec.'), 
	`parallax` FLOAT64 OPTIONS(description='Parallax.'), 
	`parallaxErr` FLOAT64 OPTIONS(description='Uncertainty of parallax.'), 
	`pmRa_pmDec_Cov` FLOAT64 OPTIONS(description='Covariance of pmRa and pmDec.'), 
	`pmRa_parallax_Cov` FLOAT64 OPTIONS(description='Covariance of pmRa and parallax.'), 
	`pmDec_parallax_Cov` FLOAT64 OPTIONS(description='Covariance of pmDec and parallax.'), 
	`pmParallaxLnL` FLOAT64 OPTIONS(description='Natural log of the likelihood of the linear proper motion parallax fit.'), 
	`pmParallaxChi2` FLOAT64 OPTIONS(description='Chi^2 static of the model fit.'), 
	`pmParallaxNdata` INT64 OPTIONS(description='The number of data points used to fit the model.'), 
	`u_psfFluxMean` FLOAT64 OPTIONS(description='Weighted mean point-source model magnitude for u filter.'), 
	`u_psfFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of u_psfFluxMean.'), 
	`u_psfFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of u_psfFlux.'), 
	`u_psfFluxChi2` FLOAT64 OPTIONS(description='Chi^2 statistic for the scatter of u_psfFlux around u_psfFluxMean.'), 
	`u_psfFluxNdata` INT64 OPTIONS(description='The number of data points used to compute u_psfFluxChi2.'), 
	`u_fpFluxMean` FLOAT64 OPTIONS(description='Weighted mean forced photometry flux for u filter.'), 
	`u_fpFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of u_fpFluxMean.'), 
	`u_fpFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of u_fpFlux.'), 
	`g_psfFluxMean` FLOAT64 OPTIONS(description='Weighted mean point-source model magnitude for g filter.'), 
	`g_psfFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of g_psfFluxMean.'), 
	`g_psfFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of g_psfFlux.'), 
	`g_psfFluxChi2` FLOAT64 OPTIONS(description='Chi^2 statistic for the scatter of g_psfFlux around g_psfFluxMean.'), 
	`g_psfFluxNdata` INT64 OPTIONS(description='The number of data points used to compute g_psfFluxChi2.'), 
	`g_fpFluxMean` FLOAT64 OPTIONS(description='Weighted mean forced photometry flux for g filter.'), 
	`g_fpFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of g_fpFluxMean.'), 
	`g_fpFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of g_fpFlux.'), 
	`r_psfFluxMean` FLOAT64 OPTIONS(description='Weighted mean point-source model magnitude for r filter.'), 
	`r_psfFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of r_psfFluxMean.'), 
	`r_psfFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of r_psfFlux.'), 
	`r_psfFluxChi2` FLOAT64 OPTIONS(description='Chi^2 statistic for the scatter of r_psfFlux around r_psfFluxMean.'), 
	`r_psfFluxNdata` INT64 OPTIONS(description='The number of data points used to compute r_psfFluxChi2.'), 
	`r_fpFluxMean` FLOAT64 OPTIONS(description='Weighted mean forced photometry flux for r filter.'), 
	`r_fpFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of r_fpFluxMean.'), 
	`r_fpFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of r_fpFlux.'), 
	`i_psfFluxMean` FLOAT64 OPTIONS(description='Weighted mean point-source model magnitude for i filter.'), 
	`i_psfFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of i_psfFluxMean.'), 
	`i_psfFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of i_psfFlux.'), 
	`i_psfFluxChi2` FLOAT64 OPTIONS(description='Chi^2 statistic for the scatter of i_psfFlux around i_psfFluxMean.'), 
	`i_psfFluxNdata` INT64 OPTIONS(description='The number of data points used to compute i_psfFluxChi2.'), 
	`i_fpFluxMean` FLOAT64 OPTIONS(description='Weighted mean forced photometry flux for i filter.'), 
	`i_fpFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of i_fpFluxMean.'), 
	`i_fpFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of i_fpFlux.'), 
	`z_psfFluxMean` FLOAT64 OPTIONS(description='Weighted mean point-source model magnitude for z filter.'), 
	`z_psfFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of z_psfFluxMean.'), 
	`z_psfFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of z_psfFlux.'), 
	`z_psfFluxChi2` FLOAT64 OPTIONS(description='Chi^2 statistic for the scatter of z_psfFlux around z_psfFluxMean.'), 
	`z_psfFluxNdata` INT64 OPTIONS(description='The number of data points used to compute z_psfFluxChi2.'), 
	`z_fpFluxMean` FLOAT64 OPTIONS(description='Weighted mean forced photometry flux for z filter.'), 
	`z_fpFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of z_fpFluxMean.'), 
	`z_fpFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of z_fpFlux.'), 
	`y_psfFluxMean` FLOAT64 OPTIONS(description='Weighted mean point-source model magnitude for y filter.'), 
	`y_psfFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of y_psfFluxMean.'), 
	`y_psfFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of y_psfFlux.'), 
	`y_psfFluxChi2` FLOAT64 OPTIONS(description='Chi^2 statistic for the scatter of y_psfFlux around y_psfFluxMean.'), 
	`y_psfFluxNdata` INT64 OPTIONS(description='The number of data points used to compute y_psfFluxChi2.'), 
	`y_fpFluxMean` FLOAT64 OPTIONS(description='Weighted mean forced photometry flux for y filter.'), 
	`y_fpFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of y_fpFluxMean.'), 
	`y_fpFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of y_fpFlux.'), 
	`nearbyObj1` INT64 OPTIONS(description='Id of the closest nearby object.'), 
	`nearbyObj1Dist` FLOAT64 OPTIONS(description='Distance to nearbyObj1.'), 
	`nearbyObj1LnP` FLOAT64 OPTIONS(description='Natural log of the probability that the observed diaObject is the same as the nearbyObj1.'), 
	`nearbyObj2` INT64 OPTIONS(description='Id of the second-closest nearby object.'), 
	`nearbyObj2Dist` FLOAT64 OPTIONS(description='Distance to nearbyObj2.'), 
	`nearbyObj2LnP` FLOAT64 OPTIONS(description='Natural log of the probability that the observed diaObject is the same as the nearbyObj2.'), 
	`nearbyObj3` INT64 OPTIONS(description='Id of the third-closest nearby object.'), 
	`nearbyObj3Dist` FLOAT64 OPTIONS(description='Distance to nearbyObj3.'), 
	`nearbyObj3LnP` FLOAT64 OPTIONS(description='Natural log of the probability that the observed diaObject is the same as the nearbyObj3.'), 
	`nearbyExtObj1` INT64 OPTIONS(description='Id of the closest extended DR Object by second moment-based separation.'), 
	`nearbyExtObj1Sep` FLOAT64 OPTIONS(description='Second moment-based separation of nearbyExtObj1 (unitless).'), 
	`nearbyExtObj2` INT64 OPTIONS(description='Id of the second closest extended DR Object by second moment-based separation.'), 
	`nearbyExtObj2Sep` FLOAT64 OPTIONS(description='Second moment-based separation of nearbyExtObj2 (unitless).'), 
	`nearbyExtObj3` INT64 OPTIONS(description='Id of the third closest extended DR Object by second moment-based separation.'), 
	`nearbyExtObj3Sep` FLOAT64 OPTIONS(description='Second moment-based separation of nearbyExtObj3 (unitless).'), 
	`nearbyLowzGal` STRING(64) OPTIONS(description='External catalog name of the nearest low-z potential host.'), 
	`nearbyLowzGalSep` FLOAT64 OPTIONS(description='Separation distance of nearbyLowzGal.'), 
	`u_scienceFluxMean` FLOAT64 OPTIONS(description='Weighted mean forced photometry flux for u filter.'), 
	`u_scienceFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of u_scienceFluxMean.'), 
	`u_scienceFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of u_scienceFlux.'), 
	`g_scienceFluxMean` FLOAT64 OPTIONS(description='Weighted mean forced photometry flux for g filter.'), 
	`g_scienceFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of g_scienceFluxMean.'), 
	`g_scienceFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of g_scienceFlux.'), 
	`r_scienceFluxMean` FLOAT64 OPTIONS(description='Weighted mean forced photometry flux for r filter.'), 
	`r_scienceFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of r_scienceFluxMean.'), 
	`r_scienceFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of r_scienceFlux.'), 
	`i_scienceFluxMean` FLOAT64 OPTIONS(description='Weighted mean forced photometry flux for i filter.'), 
	`i_scienceFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of i_scienceFluxMean.'), 
	`i_scienceFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of i_scienceFlux.'), 
	`z_scienceFluxMean` FLOAT64 OPTIONS(description='Weighted mean forced photometry flux for z filter.'), 
	`z_scienceFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of z_scienceFluxMean.'), 
	`z_scienceFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of z_scienceFlux.'), 
	`y_scienceFluxMean` FLOAT64 OPTIONS(description='Weighted mean forced photometry flux for y filter.'), 
	`y_scienceFluxMeanErr` FLOAT64 OPTIONS(description='Standard error of y_scienceFluxMean.'), 
	`y_scienceFluxSigma` FLOAT64 OPTIONS(description='Standard deviation of the distribution of y_scienceFlux.'), 
	`u_psfFluxMAD` FLOAT64 OPTIONS(description='Median absolute deviation u band fluxes.'), 
	`u_psfFluxSkew` FLOAT64 OPTIONS(description='Skewness of the u band fluxes.'), 
	`u_psfFluxPercentile05` FLOAT64 OPTIONS(description='Value at the 5%% percentile of the u band fluxes.'), 
	`u_psfFluxPercentile25` FLOAT64 OPTIONS(description='Value at the 25%% percentile of the u band fluxes.'), 
	`u_psfFluxPercentile50` FLOAT64 OPTIONS(description='Value at the 50%% percentile (median) of the u band fluxes.'), 
	`u_psfFluxPercentile75` FLOAT64 OPTIONS(description='Value at the 75%% percentile of the u band fluxes.'), 
	`u_psfFluxPercentile95` FLOAT64 OPTIONS(description='Value at the 95%% percentile of the u band fluxes.'), 
	`u_psfFluxMin` FLOAT64 OPTIONS(description='Minimum observed u band fluxes.'), 
	`u_psfFluxMax` FLOAT64 OPTIONS(description='Maximum observed u band fluxes.'), 
	`u_psfFluxStetsonJ` FLOAT64 OPTIONS(description='StetsonJ statistic for the u band fluxes.'), 
	`u_psfFluxLinearSlope` FLOAT64 OPTIONS(description='Linear best fit slope of the u band fluxes.'), 
	`u_psfFluxLinearIntercept` FLOAT64 OPTIONS(description='Linear best fit Intercept of the u band fluxes.'), 
	`u_psfFluxMaxSlope` FLOAT64 OPTIONS(description='Maximum slope between u band flux obsevations max(delta_flux/delta_time).'), 
	`u_psfFluxErrMean` FLOAT64 OPTIONS(description='Mean of the u band flux errors.'), 
	`g_psfFluxMAD` FLOAT64 OPTIONS(description='Median absolute deviation g band fluxes.'), 
	`g_psfFluxSkew` FLOAT64 OPTIONS(description='Skewness of the g band fluxes.'), 
	`g_psfFluxPercentile05` FLOAT64 OPTIONS(description='Value at the 5%% percentile of the g band fluxes.'), 
	`g_psfFluxPercentile25` FLOAT64 OPTIONS(description='Value at the 25%% percentile of the g band fluxes.'), 
	`g_psfFluxPercentile50` FLOAT64 OPTIONS(description='Value at the 50%% percentile (median) of the g band fluxes.'), 
	`g_psfFluxPercentile75` FLOAT64 OPTIONS(description='Value at the 75%% percentile of the g band fluxes.'), 
	`g_psfFluxPercentile95` FLOAT64 OPTIONS(description='Value at the 95%% percentile of the g band fluxes.'), 
	`g_psfFluxMin` FLOAT64 OPTIONS(description='Minimum observed g band fluxes.'), 
	`g_psfFluxMax` FLOAT64 OPTIONS(description='Maximum observed g band fluxes.'), 
	`g_psfFluxStetsonJ` FLOAT64 OPTIONS(description='StetsonJ statistic for the g band fluxes.'), 
	`g_psfFluxLinearSlope` FLOAT64 OPTIONS(description='Linear best fit slope of the g band fluxes.'), 
	`g_psfFluxLinearIntercept` FLOAT64 OPTIONS(description='Linear best fit Intercept of the g band fluxes.'), 
	`g_psfFluxMaxSlope` FLOAT64 OPTIONS(description='Maximum slope between g band flux obsevations max(delta_flux/delta_time).'), 
	`g_psfFluxErrMean` FLOAT64 OPTIONS(description='Mean of the g band flux errors.'), 
	`r_psfFluxMAD` FLOAT64 OPTIONS(description='Median absolute deviation r band fluxes.'), 
	`r_psfFluxSkew` FLOAT64 OPTIONS(description='Skewness of the r band fluxes.'), 
	`r_psfFluxPercentile05` FLOAT64 OPTIONS(description='Value at the 5%% percentile of the r band fluxes.'), 
	`r_psfFluxPercentile25` FLOAT64 OPTIONS(description='Value at the 25%% percentile of the r band fluxes.'), 
	`r_psfFluxPercentile50` FLOAT64 OPTIONS(description='Value at the 50%% percentile (median) of the r band fluxes.'), 
	`r_psfFluxPercentile75` FLOAT64 OPTIONS(description='Value at the 75%% percentile of the r band fluxes.'), 
	`r_psfFluxPercentile95` FLOAT64 OPTIONS(description='Value at the 95%% percentile of the r band fluxes.'), 
	`r_psfFluxMin` FLOAT64 OPTIONS(description='Minimum observed r band fluxes.'), 
	`r_psfFluxMax` FLOAT64 OPTIONS(description='Maximum observed r band fluxes.'), 
	`r_psfFluxStetsonJ` FLOAT64 OPTIONS(description='StetsonJ statistic for the r band fluxes.'), 
	`r_psfFluxLinearSlope` FLOAT64 OPTIONS(description='Linear best fit slope of the r band fluxes.'), 
	`r_psfFluxLinearIntercept` FLOAT64 OPTIONS(description='Linear best fit Intercept of the r band fluxes.'), 
	`r_psfFluxMaxSlope` FLOAT64 OPTIONS(description='Maximum slope between r band flux obsevations max(delta_flux/delta_time).'), 
	`r_psfFluxErrMean` FLOAT64 OPTIONS(description='Mean of the r band flux errors.'), 
	`i_psfFluxMAD` FLOAT64 OPTIONS(description='Median absolute deviation i band fluxes.'), 
	`i_psfFluxSkew` FLOAT64 OPTIONS(description='Skewness of the i band fluxes.'), 
	`i_psfFluxPercentile05` FLOAT64 OPTIONS(description='Value at the 5%% percentile of the i band fluxes.'), 
	`i_psfFluxPercentile25` FLOAT64 OPTIONS(description='Value at the 25%% percentile of the i band fluxes.'), 
	`i_psfFluxPercentile50` FLOAT64 OPTIONS(description='Value at the 50%% percentile (median) of the i band fluxes.'), 
	`i_psfFluxPercentile75` FLOAT64 OPTIONS(description='Value at the 75%% percentile of the i band fluxes.'), 
	`i_psfFluxPercentile95` FLOAT64 OPTIONS(description='Value at the 95%% percentile of the i band fluxes.'), 
	`i_psfFluxMin` FLOAT64 OPTIONS(description='Minimum observed i band fluxes.'), 
	`i_psfFluxMax` FLOAT64 OPTIONS(description='Maximum observed i band fluxes.'), 
	`i_psfFluxStetsonJ` FLOAT64 OPTIONS(description='StetsonJ statistic for the i band fluxes.'), 
	`i_psfFluxLinearSlope` FLOAT64 OPTIONS(description='Linear best fit slope of the i band fluxes.'), 
	`i_psfFluxLinearIntercept` FLOAT64 OPTIONS(description='Linear best fit Intercept of the i band fluxes.'), 
	`i_psfFluxMaxSlope` FLOAT64 OPTIONS(description='Maximum slope between i band flux obsevations max(delta_flux/delta_time).'), 
	`i_psfFluxErrMean` FLOAT64 OPTIONS(description='Mean of the i band flux errors.'), 
	`z_psfFluxMAD` FLOAT64 OPTIONS(description='Median absolute deviation z band fluxes.'), 
	`z_psfFluxSkew` FLOAT64 OPTIONS(description='Skewness of the z band fluxes.'), 
	`z_psfFluxPercentile05` FLOAT64 OPTIONS(description='Value at the 5%% percentile of the z band fluxes.'), 
	`z_psfFluxPercentile25` FLOAT64 OPTIONS(description='Value at the 25%% percentile of the z band fluxes.'), 
	`z_psfFluxPercentile50` FLOAT64 OPTIONS(description='Value at the 50%% percentile (median) of the z band fluxes.'), 
	`z_psfFluxPercentile75` FLOAT64 OPTIONS(description='Value at the 75%% percentile of the z band fluxes.'), 
	`z_psfFluxPercentile95` FLOAT64 OPTIONS(description='Value at the 95%% percentile of the z band fluxes.'), 
	`z_psfFluxMin` FLOAT64 OPTIONS(description='Minimum observed z band fluxes.'), 
	`z_psfFluxMax` FLOAT64 OPTIONS(description='Maximum observed z band fluxes.'), 
	`z_psfFluxStetsonJ` FLOAT64 OPTIONS(description='StetsonJ statistic for the z band fluxes.'), 
	`z_psfFluxLinearSlope` FLOAT64 OPTIONS(description='Linear best fit slope of the z band fluxes.'), 
	`z_psfFluxLinearIntercept` FLOAT64 OPTIONS(description='Linear best fit Intercept of the z band fluxes.'), 
	`z_psfFluxMaxSlope` FLOAT64 OPTIONS(description='Maximum slope between z band flux obsevations max(delta_flux/delta_time).'), 
	`z_psfFluxErrMean` FLOAT64 OPTIONS(description='Mean of the z band flux errors.'), 
	`y_psfFluxMAD` FLOAT64 OPTIONS(description='Median absolute deviation y band fluxes.'), 
	`y_psfFluxSkew` FLOAT64 OPTIONS(description='Skewness of the y band fluxes.'), 
	`y_psfFluxPercentile05` FLOAT64 OPTIONS(description='Value at the 5%% percentile of the y band fluxes.'), 
	`y_psfFluxPercentile25` FLOAT64 OPTIONS(description='Value at the 25%% percentile of the y band fluxes.'), 
	`y_psfFluxPercentile50` FLOAT64 OPTIONS(description='Value at the 50%% percentile (median) of the y band fluxes.'), 
	`y_psfFluxPercentile75` FLOAT64 OPTIONS(description='Value at the 75%% percentile of the y band fluxes.'), 
	`y_psfFluxPercentile95` FLOAT64 OPTIONS(description='Value at the 95%% percentile of the y band fluxes.'), 
	`y_psfFluxMin` FLOAT64 OPTIONS(description='Minimum observed y band fluxes.'), 
	`y_psfFluxMax` FLOAT64 OPTIONS(description='Maximum observed y band fluxes.'), 
	`y_psfFluxStetsonJ` FLOAT64 OPTIONS(description='StetsonJ statistic for the y band fluxes.'), 
	`y_psfFluxLinearSlope` FLOAT64 OPTIONS(description='Linear best fit slope of the y band fluxes.'), 
	`y_psfFluxLinearIntercept` FLOAT64 OPTIONS(description='Linear best fit Intercept of the y band fluxes.'), 
	`y_psfFluxMaxSlope` FLOAT64 OPTIONS(description='Maximum slope between y band flux obsevations max(delta_flux/delta_time).'), 
	`y_psfFluxErrMean` FLOAT64 OPTIONS(description='Mean of the y band flux errors.'), 
	`lastNonForcedSource` TIMESTAMP NOT NULL OPTIONS(description='Last time when non-forced DIASource was seen for this object.'), 
	`nDiaSources` INT64 NOT NULL OPTIONS(description='Total number of DiaSources associated with this DiaObject.')
) OPTIONS(description='The DiaObject table contains descriptions of the astronomical objects detected on one or more difference images.')



--------------------------------------------------------------------------------


CREATE OR REPLACE TABLE `ppdb-dev-438721.ppdb_dev.SSObject` (
	`ssObjectId` INT64 NOT NULL OPTIONS(description='Unique identifier.'), 
	`discoverySubmissionDate` DOUBLE OPTIONS(description='The date the LSST first linked and submitted the discovery observations to the MPC. May be NULL if not an LSST discovery. The date format will follow general LSST conventions (MJD TAI, at the moment).'), 
	`firstObservationDate` DOUBLE OPTIONS(description='The time of the first LSST observation of this object (could be precovered) as Modified Julian Date, International Atomic Time.'), 
	`arc` FLOAT64 OPTIONS(description='Arc of LSST observations.'), 
	`numObs` INT64 OPTIONS(description='Number of LSST observations of this object.'), 
	`lcPeriodic` BYTES(768) OPTIONS(description='Periodic light curve features computed on phase/distance-corrected magnitudes (H), 6x32 floats.'), 
	`MOID` FLOAT64 OPTIONS(description='Minimum orbit intersection distance to Earth.'), 
	`MOIDTrueAnomaly` FLOAT64 OPTIONS(description='True anomaly of the MOID point.'), 
	`MOIDEclipticLongitude` FLOAT64 OPTIONS(description='Ecliptic longitude of the MOID point.'), 
	`MOIDDeltaV` FLOAT64 OPTIONS(description='DeltaV at the MOID point.'), 
	`u_H` FLOAT64 OPTIONS(description='Best fit absolute magnitude (u band).'), 
	`u_G12` FLOAT64 OPTIONS(description='Best fit G12 slope parameter (u band).'), 
	`u_HErr` FLOAT64 OPTIONS(description='Uncertainty of H (u band).'), 
	`u_G12Err` FLOAT64 OPTIONS(description='Uncertainty of G12 (u band).'), 
	`u_H_u_G12_Cov` FLOAT64 OPTIONS(description='H-G12 covariance (u band).'), 
	`u_Chi2` FLOAT64 OPTIONS(description='Chi^2 statistic of the phase curve fit (u band).'), 
	`u_Ndata` INT64 OPTIONS(description='The number of data points used to fit the phase curve (u band).'), 
	`g_H` FLOAT64 OPTIONS(description='Best fit absolute magnitude (g band).'), 
	`g_G12` FLOAT64 OPTIONS(description='Best fit G12 slope parameter (g band).'), 
	`g_HErr` FLOAT64 OPTIONS(description='Uncertainty of H (g band).'), 
	`g_G12Err` FLOAT64 OPTIONS(description='Uncertainty of G12 (g band).'), 
	`g_H_g_G12_Cov` FLOAT64 OPTIONS(description='H-G12 covariance (g band).'), 
	`g_Chi2` FLOAT64 OPTIONS(description='Chi^2 statistic of the phase curve fit (g band).'), 
	`g_Ndata` INT64 OPTIONS(description='The number of data points used to fit the phase curve (g band).'), 
	`r_H` FLOAT64 OPTIONS(description='Best fit absolute magnitude (r band).'), 
	`r_G12` FLOAT64 OPTIONS(description='Best fit G12 slope parameter (r band).'), 
	`r_HErr` FLOAT64 OPTIONS(description='Uncertainty of H (r band).'), 
	`r_G12Err` FLOAT64 OPTIONS(description='Uncertainty of G12 (r band).'), 
	`r_H_r_G12_Cov` FLOAT64 OPTIONS(description='H-G12 covariance (r band).'), 
	`r_Chi2` FLOAT64 OPTIONS(description='Chi^2 statistic of the phase curve fit (r band).'), 
	`r_Ndata` INT64 OPTIONS(description='The number of data points used to fit the phase curve (r band).'), 
	`i_H` FLOAT64 OPTIONS(description='Best fit absolute magnitude (i band).'), 
	`i_G12` FLOAT64 OPTIONS(description='Best fit G12 slope parameter (i band).'), 
	`i_HErr` FLOAT64 OPTIONS(description='Uncertainty of H (i band).'), 
	`i_G12Err` FLOAT64 OPTIONS(description='Uncertainty of G12 (i band).'), 
	`i_H_i_G12_Cov` FLOAT64 OPTIONS(description='H-G12 covariance (i band).'), 
	`i_Chi2` FLOAT64 OPTIONS(description='Chi^2 statistic of the phase curve fit (i band).'), 
	`i_Ndata` INT64 OPTIONS(description='The number of data points used to fit the phase curve (i band).'), 
	`z_H` FLOAT64 OPTIONS(description='Best fit absolute magnitude (z band).'), 
	`z_G12` FLOAT64 OPTIONS(description='Best fit G12 slope parameter (z band).'), 
	`z_HErr` FLOAT64 OPTIONS(description='Uncertainty of H (z band).'), 
	`z_G12Err` FLOAT64 OPTIONS(description='Uncertainty of G12 (z band).'), 
	`z_H_z_G12_Cov` FLOAT64 OPTIONS(description='H-G12 covariance (z band).'), 
	`z_Chi2` FLOAT64 OPTIONS(description='Chi^2 statistic of the phase curve fit (z band).'), 
	`z_Ndata` INT64 OPTIONS(description='The number of data points used to fit the phase curve (z band).'), 
	`y_H` FLOAT64 OPTIONS(description='Best fit absolute magnitude (y band).'), 
	`y_G12` FLOAT64 OPTIONS(description='Best fit G12 slope parameter (y band).'), 
	`y_HErr` FLOAT64 OPTIONS(description='Uncertainty of H (y band).'), 
	`y_G12Err` FLOAT64 OPTIONS(description='Uncertainty of G12 (y band).'), 
	`y_H_y_G12_Cov` FLOAT64 OPTIONS(description='H-G12 covariance (y band).'), 
	`y_Chi2` FLOAT64 OPTIONS(description='Chi^2 statistic of the phase curve fit (y band).'), 
	`y_Ndata` INT64 OPTIONS(description='The number of data points used to fit the phase curve (y band).'), 
	`maxExtendedness` FLOAT64 OPTIONS(description='maximum `extendedness` value from the DIASource.'), 
	`minExtendedness` FLOAT64 OPTIONS(description='minimum `extendedness` value from the DIASource.'), 
	`medianExtendedness` FLOAT64 OPTIONS(description='median `extendedness` value from the DIASource.')
) OPTIONS(description='LSST-computed per-object quantities. 1:1 relationship with MPCORB. Recomputed daily, upon MPCORB ingestion.')



--------------------------------------------------------------------------------


CREATE OR REPLACE TABLE `ppdb-dev-438721.ppdb_dev.DiaSource` (
	`diaSourceId` INT64 NOT NULL OPTIONS(description='Unique identifier of this DiaSource.'), 
	`visit` INT64 NOT NULL OPTIONS(description='Id of the visit where this diaSource was measured.'), 
	`detector` INT64 NOT NULL OPTIONS(description='Id of the detector where this diaSource was measured. Datatype short instead of byte because of DB concerns about unsigned bytes.'), 
	`diaObjectId` INT64 OPTIONS(description='Id of the diaObject this source was associated with, if any. If not, it is set to NULL (each diaSource will be associated with either a diaObject or ssObject).'), 
	`ssObjectId` INT64 OPTIONS(description='Id of the ssObject this source was associated with, if any. If not, it is set to NULL (each diaSource will be associated with either a diaObject or ssObject).'), 
	`parentDiaSourceId` INT64 OPTIONS(description='Id of the parent diaSource this diaSource has been deblended from, if any.'), 
	`ssObjectReassocTime` TIMESTAMP OPTIONS(description='Time when this diaSource was reassociated from diaObject to ssObject (if such reassociation happens, otherwise NULL).'), 
	`midpointMjdTai` DOUBLE NOT NULL OPTIONS(description='Effective mid-visit time for this diaSource, expressed as Modified Julian Date, International Atomic Time.'), 
	`ra` DOUBLE NOT NULL OPTIONS(description='Right ascension coordinate of the center of this diaSource.'), 
	`raErr` FLOAT64 OPTIONS(description='Uncertainty of ra.'), 
	`dec` DOUBLE NOT NULL OPTIONS(description='Declination coordinate of the center of this diaSource.'), 
	`decErr` FLOAT64 OPTIONS(description='Uncertainty of dec.'), 
	`ra_dec_Cov` FLOAT64 OPTIONS(description='Covariance between ra and dec.'), 
	`x` FLOAT64 NOT NULL OPTIONS(description='x position computed by a centroiding algorithm.'), 
	`xErr` FLOAT64 OPTIONS(description='Uncertainty of x.'), 
	`y` FLOAT64 NOT NULL OPTIONS(description='y position computed by a centroiding algorithm.'), 
	`yErr` FLOAT64 OPTIONS(description='Uncertainty of y.'), 
	`x_y_Cov` FLOAT64 OPTIONS(description='Covariance between x and y.'), 
	`centroid_flag` BOOL OPTIONS(description='General centroid algorithm failure flag; set if anything went wrong when fitting the centroid. Another centroid flag field should also be set to provide more information.'), 
	`apFlux` FLOAT64 OPTIONS(description='Flux in a 12 pixel radius aperture on the difference image.'), 
	`apFluxErr` FLOAT64 OPTIONS(description='Estimated uncertainty of apFlux.'), 
	`apFlux_flag` BOOL OPTIONS(description='General aperture flux algorithm failure flag; set if anything went wrong when measuring aperture fluxes. Another apFlux flag field should also be set to provide more information.'), 
	`apFlux_flag_apertureTruncated` BOOL OPTIONS(description='Aperture did not fit within measurement image.'), 
	`is_negative` BOOL OPTIONS(description='Source was detected as significantly negative.'), 
	`snr` FLOAT64 OPTIONS(description='The signal-to-noise ratio at which this source was detected in the difference image.'), 
	`psfFlux` FLOAT64 OPTIONS(description='Flux for Point Source model. Note this actually measures the flux difference between the template and the visit image.'), 
	`psfFluxErr` FLOAT64 OPTIONS(description='Uncertainty of psfFlux.'), 
	`psfRa` DOUBLE OPTIONS(description='Right ascension coordinate of centroid for point source model.'), 
	`psfRaErr` FLOAT64 OPTIONS(description='Uncertainty of psfRa.'), 
	`psfDec` DOUBLE OPTIONS(description='Declination coordinate of centroid for point source model.'), 
	`psfDecErr` FLOAT64 OPTIONS(description='Uncertainty of psfDec.'), 
	`psfFlux_psfRa_Cov` FLOAT64 OPTIONS(description='Covariance between psfFlux and psfRa.'), 
	`psfFlux_psfDec_Cov` FLOAT64 OPTIONS(description='Covariance between psfFlux and psfDec.'), 
	`psfRa_psfDec_Cov` FLOAT64 OPTIONS(description='Covariance between psfRa and psfDec.'), 
	`psfLnL` FLOAT64 OPTIONS(description='Natural log likelihood of the observed data given the point source model.'), 
	`psfChi2` FLOAT64 OPTIONS(description='Chi^2 statistic of the point source model fit.'), 
	`psfNdata` INT64 OPTIONS(description='The number of data points (pixels) used to fit the point source model.'), 
	`psfFlux_flag` BOOL OPTIONS(description='Failure to derive linear least-squares fit of psf model. Another psfFlux flag field should also be set to provide more information.'), 
	`psfFlux_flag_edge` BOOL OPTIONS(description='Object was too close to the edge of the image to use the full PSF model.'), 
	`psfFlux_flag_noGoodPixels` BOOL OPTIONS(description='Not enough non-rejected pixels in data to attempt the fit.'), 
	`trailFlux` FLOAT64 OPTIONS(description='Flux for a trailed source model. Note this actually measures the flux difference between the template and the visit image.'), 
	`trailFluxErr` FLOAT64 OPTIONS(description='Uncertainty of trailFlux.'), 
	`trailRa` DOUBLE OPTIONS(description='Right ascension coordinate of centroid for trailed source model.'), 
	`trailRaErr` FLOAT64 OPTIONS(description='Uncertainty of trailRa.'), 
	`trailDec` DOUBLE OPTIONS(description='Declination coordinate of centroid for trailed source model.'), 
	`trailDecErr` FLOAT64 OPTIONS(description='Uncertainty of trailDec.'), 
	`trailLength` FLOAT64 OPTIONS(description='Maximum likelihood fit of trail length.'), 
	`trailLengthErr` FLOAT64 OPTIONS(description='Uncertainty of trailLength.'), 
	`trailAngle` FLOAT64 OPTIONS(description='Maximum likelihood fit of the angle between the meridian through the centroid and the trail direction (bearing).'), 
	`trailAngleErr` FLOAT64 OPTIONS(description='Uncertainty of trailAngle.'), 
	`trailFlux_trailRa_Cov` FLOAT64 OPTIONS(description='Covariance of trailFlux and trailRa.'), 
	`trailFlux_trailDec_Cov` FLOAT64 OPTIONS(description='Covariance of trailFlux and trailDec.'), 
	`trailFlux_trailLength_Cov` FLOAT64 OPTIONS(description='Covariance of trailFlux and trailLength'), 
	`trailFlux_trailAngle_Cov` FLOAT64 OPTIONS(description='Covariance of trailFlux and trailAngle'), 
	`trailRa_trailDec_Cov` FLOAT64 OPTIONS(description='Covariance of trailRa and trailDec.'), 
	`trailRa_trailLength_Cov` FLOAT64 OPTIONS(description='Covariance of trailRa and trailLength.'), 
	`trailRa_trailAngle_Cov` FLOAT64 OPTIONS(description='Covariance of trailRa and trailAngle.'), 
	`trailDec_trailLength_Cov` FLOAT64 OPTIONS(description='Covariance of trailDec and trailLength.'), 
	`trailDec_trailAngle_Cov` FLOAT64 OPTIONS(description='Covariance of trailDec and trailAngle.'), 
	`trailLength_trailAngle_Cov` FLOAT64 OPTIONS(description='Covariance of trailLength and trailAngle'), 
	`trailLnL` FLOAT64 OPTIONS(description='Natural log likelihood of the observed data given the trailed source model.'), 
	`trailChi2` FLOAT64 OPTIONS(description='Chi^2 statistic of the trailed source model fit.'), 
	`trailNdata` INT64 DEFAULT 0 OPTIONS(description='The number of data points (pixels) used to fit the trailed source model.'), 
	`trail_flag_edge` BOOL OPTIONS(description='This flag is set if a trailed source extends onto or past edge pixels.'), 
	`dipoleMeanFlux` FLOAT64 OPTIONS(description='Maximum likelihood value for the mean absolute flux of the two lobes for a dipole model.'), 
	`dipoleMeanFluxErr` FLOAT64 OPTIONS(description='Uncertainty of dipoleMeanFlux.'), 
	`dipoleFluxDiff` FLOAT64 OPTIONS(description='Maximum likelihood value for the difference of absolute fluxes of the two lobes for a dipole model.'), 
	`dipoleFluxDiffErr` FLOAT64 OPTIONS(description='Uncertainty of dipoleFluxDiff.'), 
	`dipoleRa` DOUBLE OPTIONS(description='Right ascension coordinate of centroid for dipole model.'), 
	`dipoleRaErr` FLOAT64 OPTIONS(description='Uncertainty of dipoleRa.'), 
	`dipoleDec` DOUBLE OPTIONS(description='Declination coordinate of centroid for dipole model.'), 
	`dipoleDecErr` FLOAT64 OPTIONS(description='Uncertainty of dipoleDec.'), 
	`dipoleLength` FLOAT64 OPTIONS(description='Maximum likelihood value for the lobe separation in dipole model.'), 
	`dipoleLengthErr` FLOAT64 OPTIONS(description='Uncertainty of dipoleLength.'), 
	`dipoleAngle` FLOAT64 OPTIONS(description='Maximum likelihood fit of the angle between the meridian through the centroid and the dipole direction (bearing, from negative to positive lobe).'), 
	`dipoleAngleErr` FLOAT64 OPTIONS(description='Uncertainty of dipoleAngle.'), 
	`dipoleMeanFlux_dipoleFluxDiff_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleMeanFlux and dipoleFluxDiff.'), 
	`dipoleMeanFlux_dipoleRa_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleMeanFlux and dipoleRa.'), 
	`dipoleMeanFlux_dipoleDec_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleMeanFlux and dipoleDec.'), 
	`dipoleMeanFlux_dipoleLength_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleMeanFlux and dipoleLength.'), 
	`dipoleMeanFlux_dipoleAngle_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleMeanFlux and dipoleAngle.'), 
	`dipoleFluxDiff_dipoleRa_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleFluxDiff and dipoleRa.'), 
	`dipoleFluxDiff_dipoleDec_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleFluxDiff and dipoleDec.'), 
	`dipoleFluxDiff_dipoleLength_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleFluxDiff and dipoleLength.'), 
	`dipoleFluxDiff_dipoleAngle_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleFluxDiff and dipoleAngle.'), 
	`dipoleRa_dipoleDec_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleRa and dipoleDec.'), 
	`dipoleRa_dipoleLength_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleRa and dipoleLength.'), 
	`dipoleRa_dipoleAngle_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleRa and dipoleAngle.'), 
	`dipoleDec_dipoleLength_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleDec and dipoleLength.'), 
	`dipoleDec_dipoleAngle_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleDec and dipoleAngle.'), 
	`dipoleLength_dipoleAngle_Cov` FLOAT64 OPTIONS(description='Covariance of dipoleLength and dipoleAngle.'), 
	`dipoleLnL` FLOAT64 OPTIONS(description='Natural log likelihood of the observed data given the dipole source model.'), 
	`dipoleChi2` FLOAT64 OPTIONS(description='Chi^2 statistic of the model fit.'), 
	`dipoleNdata` INT64 OPTIONS(description='The number of data points (pixels) used to fit the model.'), 
	`scienceFlux` FLOAT64 OPTIONS(description='Forced photometry flux for a point source model measured on the visit image centered at DiaSource position.'), 
	`scienceFluxErr` FLOAT64 OPTIONS(description='Estimated uncertainty of scienceFlux.'), 
	`forced_PsfFlux_flag` BOOL OPTIONS(description='Forced PSF photometry on science image failed. Another forced_PsfFlux flag field should also be set to provide more information.'), 
	`forced_PsfFlux_flag_edge` BOOL OPTIONS(description='Forced PSF flux on science image was too close to the edge of the image to use the full PSF model.'), 
	`forced_PsfFlux_flag_noGoodPixels` BOOL OPTIONS(description='Forced PSF flux not enough non-rejected pixels in data to attempt the fit.'), 
	`snapDiffFlux` FLOAT64 OPTIONS(description='Calibrated flux for Point Source model centered on radec but measured on the difference of snaps comprising this visit.'), 
	`snapDiffFluxErr` FLOAT64 OPTIONS(description='Estimated uncertainty of snapDiffFlux.'), 
	`fpBkgd` FLOAT64 OPTIONS(description='Estimated sky background at the position (centroid) of the object.'), 
	`fpBkgdErr` FLOAT64 OPTIONS(description='Estimated uncertainty of fpBkgd.'), 
	`ixx` FLOAT64 OPTIONS(description='Adaptive second moment of the source intensity.'), 
	`ixxErr` FLOAT64 OPTIONS(description='Uncertainty of ixx.'), 
	`iyy` FLOAT64 OPTIONS(description='Adaptive second moment of the source intensity.'), 
	`iyyErr` FLOAT64 OPTIONS(description='Uncertainty of iyy.'), 
	`ixy` FLOAT64 OPTIONS(description='Adaptive second moment of the source intensity.'), 
	`ixyErr` FLOAT64 OPTIONS(description='Uncertainty of ixy.'), 
	`ixx_iyy_Cov` FLOAT64 OPTIONS(description='Covariance of ixx and iyy.'), 
	`ixx_ixy_Cov` FLOAT64 OPTIONS(description='Covariance of ixx and ixy.'), 
	`iyy_ixy_Cov` FLOAT64 OPTIONS(description='Covariance of iyy and ixy.'), 
	`ixxPSF` FLOAT64 OPTIONS(description='Adaptive second moment for the PSF.'), 
	`iyyPSF` FLOAT64 OPTIONS(description='Adaptive second moment for the PSF.'), 
	`ixyPSF` FLOAT64 OPTIONS(description='Adaptive second moment for the PSF.'), 
	`shape_flag` BOOL OPTIONS(description='General source shape algorithm failure flag; set if anything went wrong when measuring the shape. Another shape flag field should also be set to provide more information.'), 
	`shape_flag_no_pixels` BOOL OPTIONS(description='No pixels to measure shape.'), 
	`shape_flag_not_contained` BOOL OPTIONS(description='Center not contained in footprint bounding box.'), 
	`shape_flag_parent_source` BOOL OPTIONS(description='This source is a parent source; we should only be measuring on deblended children in difference imaging.'), 
	`extendedness` FLOAT64 OPTIONS(description="A measure of extendedness, computed by comparing an object's moment-based traced radius to the PSF moments. extendedness = 1 implies a high degree of confidence that the source is extended. extendedness = 0 implies a high degree of confidence that the source is point-like."), 
	`reliability` FLOAT64 OPTIONS(description='A measure of reliability, computed using information from the source and image characterization, as well as the information on the Telescope and Camera system (e.g., ghost maps, defect maps, etc.).'), 
	`band` STRING(1) OPTIONS(description='Filter band this source was observed with.'), 
	`isDipole` BOOL OPTIONS(description='Source well fit by a dipole.'), 
	`dipoleFitAttempted` BOOL OPTIONS(description='Attempted to fit a dipole model to this source.'), 
	`time_processed` TIMESTAMP NOT NULL OPTIONS(description='Time when the image was processed and this DiaSource record was generated.'), 
	`time_withdrawn` TIMESTAMP OPTIONS(description='Time when this record was marked invalid.'), 
	`bboxSize` INT64, 
	`pixelFlags` BOOL OPTIONS(description="General pixel flags failure; set if anything went wrong when setting pixels flags from this footprint's mask. This implies that some pixelFlags for this source may be incorrectly set to False."), 
	`pixelFlags_bad` BOOL OPTIONS(description='Bad pixel in the DiaSource footprint.'), 
	`pixelFlags_cr` BOOL OPTIONS(description='Cosmic ray in the DiaSource footprint.'), 
	`pixelFlags_crCenter` BOOL OPTIONS(description='Cosmic ray in the 3x3 region around the centroid.'), 
	`pixelFlags_edge` BOOL OPTIONS(description='Some of the source footprint is outside usable exposure region (masked EDGE or centroid off image).'), 
	`pixelFlags_nodata` BOOL OPTIONS(description='NO_DATA pixel in the source footprint.'), 
	`pixelFlags_nodataCenter` BOOL OPTIONS(description='NO_DATA pixel in the 3x3 region around the centroid.'), 
	`pixelFlags_interpolated` BOOL OPTIONS(description='Interpolated pixel in the DiaSource footprint.'), 
	`pixelFlags_interpolatedCenter` BOOL OPTIONS(description='Interpolated pixel in the 3x3 region around the centroid.'), 
	`pixelFlags_offimage` BOOL OPTIONS(description='DiaSource center is off image.'), 
	`pixelFlags_saturated` BOOL OPTIONS(description='Saturated pixel in the DiaSource footprint.'), 
	`pixelFlags_saturatedCenter` BOOL OPTIONS(description='Saturated pixel in the 3x3 region around the centroid.'), 
	`pixelFlags_suspect` BOOL OPTIONS(description="DiaSource's footprint includes suspect pixels."), 
	`pixelFlags_suspectCenter` BOOL OPTIONS(description='Suspect pixel in the 3x3 region around the centroid.'), 
	`pixelFlags_streak` BOOL OPTIONS(description='Streak in the DiaSource footprint.'), 
	`pixelFlags_streakCenter` BOOL OPTIONS(description='Streak in the 3x3 region around the centroid.'), 
	`pixelFlags_injected` BOOL OPTIONS(description='Injection in the DiaSource footprint.'), 
	`pixelFlags_injectedCenter` BOOL OPTIONS(description='Injection in the 3x3 region around the centroid.'), 
	`pixelFlags_injected_template` BOOL OPTIONS(description='Template injection in the DiaSource footprint.'), 
	`pixelFlags_injected_templateCenter` BOOL OPTIONS(description='Template injection in the 3x3 region around the centroid.')
) OPTIONS(description="Table to store 'difference image sources'; - sources detected at SNR >=5 on difference images.")



--------------------------------------------------------------------------------


CREATE OR REPLACE TABLE `ppdb-dev-438721.ppdb_dev.DiaForcedSource` (
	`diaForcedSourceId` INT64 NOT NULL OPTIONS(description='Unique id.'), 
	`diaObjectId` INT64 NOT NULL OPTIONS(description='Id of the DiaObject that this DiaForcedSource was associated with.'), 
	`ra` DOUBLE NOT NULL OPTIONS(description='Right ascension coordinate of the position of the DiaObject at time radecMjdTai.'), 
	`dec` DOUBLE NOT NULL OPTIONS(description='Declination coordinate of the position of the DiaObject at time radecMjdTai.'), 
	`visit` INT64 NOT NULL OPTIONS(description='Id of the visit where this forcedSource was measured.'), 
	`detector` INT64 NOT NULL OPTIONS(description='Id of the detector where this forcedSource was measured. Datatype short instead of byte because of DB concerns about unsigned bytes.'), 
	`psfFlux` FLOAT64 OPTIONS(description='Point Source model flux.'), 
	`psfFluxErr` FLOAT64 OPTIONS(description='Uncertainty of psfFlux.'), 
	`midpointMjdTai` DOUBLE NOT NULL OPTIONS(description='Effective mid-visit time for this diaForcedSource, expressed as Modified Julian Date, International Atomic Time.'), 
	`scienceFlux` FLOAT64 OPTIONS(description='Forced photometry flux for a point source model measured on the visit image centered at the DiaObject position.'), 
	`scienceFluxErr` FLOAT64 OPTIONS(description='Uncertainty of scienceFlux.'), 
	`band` STRING(1) OPTIONS(description='Filter band this source was observed with.'), 
	`time_processed` TIMESTAMP NOT NULL OPTIONS(description='Time when this record was generated.'), 
	`time_withdrawn` TIMESTAMP OPTIONS(description='Time when this record was marked invalid.')
) OPTIONS(description='Forced-photometry source measurement on an individual difference Exposure for all objects in the DiaObject table.')



--------------------------------------------------------------------------------


CREATE OR REPLACE TABLE `ppdb-dev-438721.ppdb_dev.DiaObject_To_Object_Match` (
	`diaObjectId` INT64 NOT NULL OPTIONS(description='Id of diaObject.'), 
	`objectId` INT64 NOT NULL OPTIONS(description='Id of a nearby object.'), 
	`dist` FLOAT64 OPTIONS(description='The distance between the diaObject and the object.'), 
	`lnP` FLOAT64 OPTIONS(description='Natural log of the probability that the observed diaObject is the same as the nearby object.')
) OPTIONS(description='The table stores mapping of diaObjects to the nearby objects.')



--------------------------------------------------------------------------------


CREATE OR REPLACE TABLE `ppdb-dev-438721.ppdb_dev.DiaObjectLast` (
	`diaObjectId` INT64 NOT NULL OPTIONS(description='Unique id.'), 
	`lastNonForcedSource` TIMESTAMP NOT NULL OPTIONS(description='Last time when non-forced DIASource was seen for this object.'), 
	`ra` DOUBLE NOT NULL OPTIONS(description='Right ascension coordinate of the position of the object at time radecMjdTai.'), 
	`raErr` FLOAT64 OPTIONS(description='Uncertainty of ra.'), 
	`dec` DOUBLE NOT NULL OPTIONS(description='Declination coordinate of the position of the object at time radecMjdTai.'), 
	`decErr` FLOAT64 OPTIONS(description='Uncertainty of dec.'), 
	`ra_dec_Cov` FLOAT64 OPTIONS(description='Covariance between ra and dec.'), 
	`radecMjdTai` DOUBLE NOT NULL OPTIONS(description='Time at which the object was at a position ra/dec, expressed as Modified Julian Date, International Atomic Time.'), 
	`pmRa` FLOAT64 OPTIONS(description='Proper motion (RA).'), 
	`pmRaErr` FLOAT64 OPTIONS(description='Uncertainty of pmRa.'), 
	`pmDec` FLOAT64 OPTIONS(description='Proper motion (Dec).'), 
	`pmDecErr` FLOAT64 OPTIONS(description='Uncertainty of pmDec.'), 
	`parallax` FLOAT64 OPTIONS(description='Parallax.'), 
	`parallaxErr` FLOAT64 OPTIONS(description='Uncertainty of parallax.'), 
	`pmRa_pmDec_Cov` FLOAT64 OPTIONS(description='Covariance of pmRa and pmDec.'), 
	`pmRa_parallax_Cov` FLOAT64 OPTIONS(description='Covariance of pmRa and parallax.'), 
	`pmDec_parallax_Cov` FLOAT64 OPTIONS(description='Covariance of pmDec and parallax.'), 
	`nDiaSources` INT64 NOT NULL OPTIONS(description='Total number of DiaSources associated with this DiaObject.')
) OPTIONS(description='Table with a subset of DiaObject columns used to store only the latest version of each object.')



--------------------------------------------------------------------------------


CREATE OR REPLACE TABLE `ppdb-dev-438721.ppdb_dev.MPCORB` (
	`mpcDesignation` STRING(8) OPTIONS(description='Number or provisional designation (in packed form).'), 
	`mpcNumber` INT64 OPTIONS(description='MPC number (if the asteroid has been numbered; NULL otherwise). Provided for convenience.'), 
	`ssObjectId` INT64 OPTIONS(description='LSST unique identifier (if observed by LSST).'), 
	`mpcH` FLOAT64 OPTIONS(description='Absolute magnitude, H.'), 
	`mpcG` FLOAT64 OPTIONS(description='Slope parameter, G.'), 
	`epoch` DOUBLE OPTIONS(description='Epoch (in MJD, .0 TT).'), 
	`M` DOUBLE OPTIONS(description='Mean anomaly at the epoch, in degrees.'), 
	`peri` DOUBLE OPTIONS(description='Argument of perihelion, J2000.0 (degrees).'), 
	`node` DOUBLE OPTIONS(description='Longitude of the ascending node, J2000.0 (degrees).'), 
	`incl` DOUBLE OPTIONS(description='Inclination to the ecliptic, J2000.0 (degrees).'), 
	`e` DOUBLE OPTIONS(description='Orbital eccentricity.'), 
	`n` DOUBLE OPTIONS(description='Mean daily motion (degrees per day).'), 
	`a` DOUBLE OPTIONS(description='Semimajor axis (AU).'), 
	`uncertaintyParameter` STRING(1) OPTIONS(description='Uncertainty parameter, U.'), 
	`reference` STRING(9) OPTIONS(description='Reference.'), 
	`nobs` INT64 OPTIONS(description='Number of observations.'), 
	`nopp` INT64 OPTIONS(description='Number of oppositions.'), 
	`arc` FLOAT64 OPTIONS(description='Arc (days), for single-opposition objects.'), 
	`arcStart` TIMESTAMP OPTIONS(description='Year of first observation (for multi-opposition objects).'), 
	`arcEnd` TIMESTAMP OPTIONS(description='Year of last observation (for multi-opposition objects).'), 
	`rms` FLOAT64 OPTIONS(description='r.m.s residual (arcsec).'), 
	`pertsShort` STRING(3) OPTIONS(description="Coarse indicator of perturbers (blank if unperturbed one-opposition. object)'"), 
	`pertsLong` STRING(3) OPTIONS(description="Precise indicator of perturbers (blank if unperturbed one-opposition. object)'"), 
	`computer` STRING(10) OPTIONS(description='Computer name.'), 
	`flags` INT64 OPTIONS(description="4-hexdigit flags. See https://minorplanetcenter.net//iau/info/MPOrbitFormat.html. for details'"), 
	`fullDesignation` STRING(26) OPTIONS(description='Readable designation.'), 
	`lastIncludedObservation` FLOAT64 OPTIONS(description='Date of last observation included in orbit solution.')
) OPTIONS(description='The orbit catalog produced by the Minor Planet Center. Ingested daily. O(10M) rows by survey end. The columns are described at https://minorplanetcenter.net//iau/info/MPOrbitFormat.html')



--------------------------------------------------------------------------------


CREATE OR REPLACE TABLE `ppdb-dev-438721.ppdb_dev.MPCORBDESIGMAP` (
	`mpcDesignation` STRING(8) OPTIONS(description='Either the MPC provisional or permanent designation.'), 
	`mpcNumber` INT64 OPTIONS(description='MPC number (if the asteroid has been numbered).'), 
	`otherDesignation` STRING(8) OPTIONS(description='Other designation by which this object is known.'), 
	`ssObjectId` INT64 OPTIONS(description='LSST unique identifier (if observed by LSST).')
) OPTIONS(description='The mapping between old and new provisional MPC designation, produced by the Minor Planet Center. Ingested daily. O(few x 10M) rows by survey end.')



--------------------------------------------------------------------------------


CREATE OR REPLACE TABLE `ppdb-dev-438721.ppdb_dev.SSSource` (
	`ssObjectId` INT64 OPTIONS(description='Unique identifier of the object.'), 
	`diaSourceId` INT64 OPTIONS(description='Unique identifier of the observation.'), 
	`mpcUniqueId` INT64 OPTIONS(description='MPC unique identifier of the observation.'), 
	`nearbyObj1` INT64 OPTIONS(description='Closest Objects (3 stars and 3 galaxies) in Level 2 database.'), 
	`nearbyObj2` INT64 OPTIONS(description='Closest Objects (3 stars and 3 galaxies) in Level 2 database.'), 
	`nearbyObj3` INT64 OPTIONS(description='Closest Objects (3 stars and 3 galaxies) in Level 2 database.'), 
	`nearbyObj4` INT64 OPTIONS(description='Closest Objects (3 stars and 3 galaxies) in Level 2 database.'), 
	`nearbyObj5` INT64 OPTIONS(description='Closest Objects (3 stars and 3 galaxies) in Level 2 database.'), 
	`nearbyObj6` INT64 OPTIONS(description='Closest Objects (3 stars and 3 galaxies) in Level 2 database.'), 
	`nearbyObjDist1` FLOAT64 OPTIONS(description='Distances to nearbyObj.'), 
	`nearbyObjDist2` FLOAT64 OPTIONS(description='Distances to nearbyObj.'), 
	`nearbyObjDist3` FLOAT64 OPTIONS(description='Distances to nearbyObj.'), 
	`nearbyObjDist4` FLOAT64 OPTIONS(description='Distances to nearbyObj.'), 
	`nearbyObjDist5` FLOAT64 OPTIONS(description='Distances to nearbyObj.'), 
	`nearbyObjDist6` FLOAT64 OPTIONS(description='Distances to nearbyObj.'), 
	`nearbyObjLnP1` FLOAT64 OPTIONS(description='Natural log of the probability that the observed DIAObject is the same as the nearby Object.'), 
	`nearbyObjLnP2` FLOAT64 OPTIONS(description='Natural log of the probability that the observed DIAObject is the same as the nearby Object.'), 
	`nearbyObjLnP3` FLOAT64 OPTIONS(description='Natural log of the probability that the observed DIAObject is the same as the nearby Object.'), 
	`nearbyObjLnP4` FLOAT64 OPTIONS(description='Natural log of the probability that the observed DIAObject is the same as the nearby Object.'), 
	`nearbyObjLnP5` FLOAT64 OPTIONS(description='Natural log of the probability that the observed DIAObject is the same as the nearby Object.'), 
	`nearbyObjLnP6` FLOAT64 OPTIONS(description='Natural log of the probability that the observed DIAObject is the same as the nearby Object.'), 
	`eclipticLambda` DOUBLE OPTIONS(description='Ecliptic longitude.'), 
	`eclipticBeta` DOUBLE OPTIONS(description='Ecliptic latitude.'), 
	`galacticL` DOUBLE OPTIONS(description='Galactic longitude.'), 
	`galacticB` DOUBLE OPTIONS(description='Galactic latitute.'), 
	`phaseAngle` FLOAT64 OPTIONS(description='Phase angle.'), 
	`heliocentricDist` FLOAT64 OPTIONS(description='Heliocentric distance.'), 
	`topocentricDist` FLOAT64 OPTIONS(description='Topocentric distace.'), 
	`predictedMagnitude` FLOAT64 OPTIONS(description='Predicted magnitude.'), 
	`predictedMagnitudeSigma` FLOAT64 OPTIONS(description='Prediction uncertainty (1-sigma).'), 
	`residualRa` DOUBLE OPTIONS(description='Residual R.A. vs. ephemeris.'), 
	`residualDec` DOUBLE OPTIONS(description='Residual Dec vs. ephemeris.'), 
	`predictedRaSigma` FLOAT64 OPTIONS(description='Predicted R.A. uncertainty.'), 
	`predictedDecSigma` FLOAT64 OPTIONS(description='Predicted Dec uncertainty.'), 
	`predictedRaDecCov` FLOAT64 OPTIONS(description='Predicted R.A./Dec covariance.'), 
	`heliocentricX` FLOAT64 OPTIONS(description='Cartesian heliocentric X coordinate (at the emit time).'), 
	`heliocentricY` FLOAT64 OPTIONS(description='Cartesian heliocentric Y coordinate (at the emit time).'), 
	`heliocentricZ` FLOAT64 OPTIONS(description='Cartesian heliocentric Z coordinate (at the emit time).'), 
	`heliocentricVX` FLOAT64 OPTIONS(description='Cartesian heliocentric X velocity (at the emit time).'), 
	`heliocentricVY` FLOAT64 OPTIONS(description='Cartesian heliocentric Y velocity (at the emit time).'), 
	`heliocentricVZ` FLOAT64 OPTIONS(description='Cartesian heliocentric Z velocity (at the emit time).'), 
	`topocentricX` FLOAT64 OPTIONS(description='Cartesian topocentric X coordinate (at the emit time).'), 
	`topocentricY` FLOAT64 OPTIONS(description='Cartesian topocentric Y coordinate (at the emit time).'), 
	`topocentricZ` FLOAT64 OPTIONS(description='Cartesian topocentric Z coordinate (at the emit time).'), 
	`topocentricVX` FLOAT64 OPTIONS(description='Cartesian topocentric X velocity (at the emit time).'), 
	`topocentricVY` FLOAT64 OPTIONS(description='Cartesian topocentric Y velocity (at the emit time).'), 
	`topocentricVZ` FLOAT64 OPTIONS(description='Cartesian topocentric Z velocity (at the emit time).')
) OPTIONS(description='LSST-computed per-source quantities. 1:1 relationship with DIASource. Recomputed daily, upon MPCORB ingestion.')



--------------------------------------------------------------------------------


CREATE OR REPLACE TABLE `ppdb-dev-438721.ppdb_dev.DetectorVisitProcessingSummary` (
	`visit` INT64 NOT NULL OPTIONS(description='Id of the visit this visit was a part of.'), 
	`detector` INT64 NOT NULL OPTIONS(description='Id of the detector on the instrument that took this visit. Datatype short instead of byte because of DB concerns about unsigned bytes.'), 
	`ra` DOUBLE OPTIONS(description='Right Ascension of detector center.'), 
	`dec` DOUBLE OPTIONS(description='Declination of detector center.'), 
	`pixelScale` FLOAT64 OPTIONS(description='Measured detector pixel scale.'), 
	`zeroPoint` FLOAT64 OPTIONS(description='Zero-point for the detector, estimated at detector center.'), 
	`psfSigma` FLOAT64 OPTIONS(description='PSF model second-moments determinant radius (center of detector).'), 
	`skyBg` FLOAT64 OPTIONS(description='Average sky background.'), 
	`skyNoise` FLOAT64 OPTIONS(description='RMS noise of the sky background.'), 
	`seeing` DOUBLE OPTIONS(description='Mean measured FWHM of the PSF.'), 
	`xSize` INT64 OPTIONS(description='Number of columns in the image.'), 
	`ySize` INT64 OPTIONS(description='Number of rows in the image.'), 
	`llcra` DOUBLE OPTIONS(description='RA of lower left corner.'), 
	`llcdec` DOUBLE OPTIONS(description='Declination of lower left corner.'), 
	`ulcra` DOUBLE OPTIONS(description='RA of upper left corner.'), 
	`ulcdec` DOUBLE OPTIONS(description='Declination of upper left corner.'), 
	`urcra` DOUBLE OPTIONS(description='RA of upper right corner.'), 
	`urcdec` DOUBLE OPTIONS(description='Declination of upper right corner.'), 
	`lrcra` DOUBLE OPTIONS(description='RA of lower right corner.'), 
	`lrcdec` DOUBLE OPTIONS(description='Declination of lower right corner.'), 
	`astromOffsetMean` DOUBLE OPTIONS(description='Mean offset of astrometric calibration matches (arcsec).'), 
	`astromOffsetStd` DOUBLE OPTIONS(description='Standard deviation of offsets of astrometric calibration matches (arcsec).'), 
	`nPsfStar` INT64 OPTIONS(description='Number of stars used for PSF model.'), 
	`psfStarDeltaE1Median` DOUBLE OPTIONS(description='Median E1 residual (starE1 - psfE1) for psf stars.'), 
	`psfStarDeltaE2Median` DOUBLE OPTIONS(description='Median E2 residual (starE2 - psfE2) for psf stars.'), 
	`psfStarDeltaE1Scatter` DOUBLE OPTIONS(description='Scatter (via MAD) of E1 residual (starE1 - psfE1) for psf stars.'), 
	`psfStarDeltaE2Scatter` DOUBLE OPTIONS(description='Scatter (via MAD) of E2 residual (starE2 - psfE2) for psf stars.'), 
	`psfStarDeltaSizeMedian` DOUBLE OPTIONS(description='Median size residual (starSize - psfSize) for psf stars (pixel).'), 
	`psfStarDeltaSizeScatter` DOUBLE OPTIONS(description='Scatter (via MAD) of size residual (starSize - psfSize) for stars (pixel).'), 
	`psfStarScaledDeltaSizeScatter` DOUBLE OPTIONS(description='Scatter (via MAD) of size residual scaled by median size squared.'), 
	`psfTraceRadiusDelta` DOUBLE OPTIONS(description='Delta (max - min) of model psf trace radius values evaluated on a grid of unmasked pixels (pixel).'), 
	`psfApFluxDelta` DOUBLE OPTIONS(description='Delta (max - min) of model psf aperture flux (with aperture radius of max(2, 3*psfSigma)) values evaluated on a grid of unmasked pixels'), 
	`psfApCorrSigmaScaledDelta` DOUBLE OPTIONS(description='Delta (max - min) of psf flux aperture correction factors scaled (divided) by the psfSigma evaluated on a grid of unmasked pixels'), 
	`maxDistToNearestPsf` DOUBLE OPTIONS(description='Maximum distance of an unmasked pixel to its nearest model psf star (pixel).')
) OPTIONS(description='Properties of an image from one processing of a single detector in a visit.')



--------------------------------------------------------------------------------

